app_admin:
    resource: "@AppBundle/Resources/config/routing/routing_admin.yml"
    prefix: /admin

app_api:
    resource: "@AppBundle/Resources/config/routing/routing_api.yml"
    prefix: /api

app_cards:
    resource: "@AppBundle/Resources/config/routing/routing_cards.yml"

app_deck:
    resource: "@AppBundle/Resources/config/routing/routing_deck.yml"
    prefix: /deck

app_decklist:
    resource: "@AppBundle/Resources/config/routing/routing_decklist.yml"
    prefix: /decklist

app_fellowship:
    resource: "@AppBundle/Resources/config/routing/routing_fellowship.yml"
    prefix: /fellowship

app_questlog:
    resource: "@AppBundle/Resources/config/routing/routing_questlog.yml"
    prefix: /questlog

app_review:
    resource: "@AppBundle/Resources/config/routing/routing_review.yml"
    prefix: /review

app_tag:
    resource: "@AppBundle/Resources/config/routing/routing_tag.yml"
    prefix: /tag

app_user:
    resource: "@AppBundle/Resources/config/routing/routing_user.yml"
    prefix: /user

app_collection:
    resource: "@AppBundle/Resources/config/routing/routing_collection.yml"
    prefix: /collection

index:
    path: /
    methods: [GET]
    defaults:
        _controller: AppBundle:Default:index

patrons:
    path: /patrons
    methods: [GET]
    defaults:
        _controller: AppBundle:Social:patrons

about:
    path: /about
    defaults:
        _controller: AppBundle:Default:about

decklist_byauthor:
    path: /d/{username}
    methods: [GET]
    defaults:
        _controller: AppBundle:Social:byauthor

fellowship_byauthor:
    path: /f/{username}
    methods: [GET]
    defaults:
        _controller: AppBundle:Fellowship:byauthor

questlogs_byauthor:
    path: /q/{username}
    methods: [GET]
    defaults:
        _controller: AppBundle:QuestLog:byauthor

decks_list:
    path: /decks
    methods: [GET]
    defaults:
        _controller: AppBundle:Builder:list

myfellowships_list:
    path: /myfellowships
    methods: [GET]
    defaults:
        _controller: AppBundle:Fellowship:mylist

myquestlogs_list:
    path: /myquestlogs/{scenario_name_canonical}/{quest_mode}
    methods: [GET]
    defaults:
        _controller: AppBundle:QuestLog:mylist
        scenario_name_canonical: null
        quest_mode: normal

questlogs_searchform:
    path: /questlogs/search
    methods: [GET]
    defaults:
        _controller: AppBundle:QuestLog:search

questlogs_list:
    path: /questlogs/{type}/{page}
    methods: [GET]
    defaults:
        _controller: AppBundle:QuestLog:list
        type: popular
        page: 1
    requirements:
        page: \d+

decklists_searchform:
    path: /decklists/search
    methods: [GET]
    defaults:
        _controller: AppBundle:Social:search

decklists_list:
    path: /decklists/{type}/{page}
    methods: [GET]
    defaults:
        _controller: AppBundle:Social:list
        type: popular
        page: 1
    requirements:
        page: \d+

fellowships_searchform:
    path: /fellowships/search
    methods: [GET]
    defaults:
        _controller: AppBundle:Fellowship:search

fellowships_list:
    path: /fellowships/{type}/{page}
    methods: [GET]
    defaults:
        _controller: AppBundle:Fellowship:list
        type: popular
        page: 1
    requirements:
        page: \d+

card_reviews_list:
    path: /reviews/{page}
    defaults:
        _controller: AppBundle:Review:list
        page: 1
    requirements:
        page: \d+

