AppBundle\Entity\QuestlogDeck:
    type: entity
    table: questlog_deck
    manyToOne:
        questlog:
            targetEntity: Questlog
            nullable: false
            inversedBy: decks
            joinColumn:
                name: questlog_id
                referencedColumnName: id
        deck:
            targetEntity: Deck
            nullable: true
            inversedBy: questlogs
            joinColumn:
                name: deck_id
                referencedColumnName: id
                onDelete: "SET NULL"
        decklist:
            targetEntity: Decklist
            nullable: true
            inversedBy: questlogs
            joinColumn:
                name: decklist_id
                referencedColumnName: id
                onDelete: "SET NULL"
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        deckNumber:
            type: smallint
            nullable: false
            column: deck_number
        player:
            type: string
            length: 80
            nullable: true
        content:
            type: text
            nullable: false